name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test_hello
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'

        - name: Install dependencies
          run: |
            python --version
            python -m pip install -r requirements_dev

        - name: Run tests
          run: pytest